// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wtgtcxtkimfuqjqbsymr.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0Z3RjeHRraW1mdXFqcWJzeW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwNzA1MzYsImV4cCI6MjA0ODY0NjUzNn0.EqGGMNofiaJ9E0LwpmUb-lAqFarzhWoRYiUt43KxXBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);